version: "3.8"

services:
  web:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app/
    command: air ./main.go -b localhost
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports: 
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis:latest
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
  testdb:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_TEST_USER}
      - POSTGRES_PASSWORD=${DB_TEST_PASSWORD}
      - POSTGRES_DB=${DB_TEST_NAME}
    ports: 
      - "5433:5433"
    volumes:
      - postgres-test-db:/var/lib/postgresql/data
    restart: always
    command: -p 5433

volumes:
  postgres-db:
  postgres-test-db: