version: "3.8"

services:
  web:
    build: ./backend
    env_file:
      - .env
    environment:
      - REDISPORT=6379
      - REDISHOST=redis
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app/backend
    command: air ./main.go -b 0.0.0.0
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports: 
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis:latest
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"

volumes:
  postgres-db: